version: "3.9"
volumes:
  my-volume:
    external: true
networks:
  mt-network:
    driver: bridge    
services:
  localhost:
    image: mysql
    restart: always
    container_name: forumsdb
    ports:
      - 4000:3306
    networks:
      - mt-network      
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=forumsdb
    volumes:
      - my-volume:/var/lib/mysql
  backend:
    build: .
    container_name: back_end
    restart: always
    ports:
      - 8071:8070
    networks:
      - mt-network   
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://localhost:3306/forumsdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - DB_HOST= mydb:4000
      - MYSQL_DATABASE=forumsdb 
    depends_on:
      - localhost  

